"""Prepare the project-local Codex integration without changing global settings."""

import json
import os
import re
import sys
from pathlib import Path
from typing import Dict

from mcp_server.dependencies import require_a_stock_data_skill
from mcp_server.workspace import WorkspaceError, load_workspace


PROJECT_SKILLS = (
    "strategy-workbench",
    "backtest-analysis",
    "daily-strategy-observer",
    "user-memory",
)


class SyncError(RuntimeError):
    """Raised when the local Agent integration cannot be prepared."""


def sync_project(root: Path, python_executable: str = None) -> Dict[str, object]:
    """Validate local dependencies and write the ignored project MCP config."""
    project_root = root.resolve()
    skill = require_a_stock_data_skill()
    try:
        workspace = load_workspace(project_root, required=True)
    except WorkspaceError as exc:
        raise SyncError(str(exc)) from exc
    skill_checks = _check_project_skills(project_root)
    config_path = project_root / ".codex" / "config.toml"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        _render_codex_config(
            project_root=project_root,
            workspace_root=workspace.root,
            workspace_db=workspace.db_path,
            workspace_calendar=workspace.calendar_path,
            python_executable=python_executable or sys.executable,
            skill_path=skill.path,
        ),
        encoding="utf-8",
    )
    return {
        "status": "ok",
        "config_path": str(config_path),
        "workspace": str(workspace.root),
        "a_stock_data_skill": {
            "name": skill.name,
            "version": skill.version,
            "path": str(skill.path),
        },
        "project_skills": skill_checks,
        "feishu_enabled": bool(
            os.getenv("FIREAGENT_ENABLE_FEISHU") == "1"
            and os.getenv("FEISHU_WEBHOOK_URL")
        ),
        "feishu_config_source": "workspace config/.env or process environment",
        "next_step": "Restart Codex or start a new task to reload the project MCP server.",
    }


def _check_project_skills(root: Path) -> Dict[str, Dict[str, str]]:
    checks: Dict[str, Dict[str, str]] = {}
    missing = []
    for name in PROJECT_SKILLS:
        path = root / "skills" / name / "SKILL.md"
        if not path.exists():
            missing.append(str(path))
            continue
        text = path.read_text(encoding="utf-8")
        if not _has_frontmatter_name(text, name):
            raise SyncError("project Skill name mismatch: {}".format(path))
        checks[name] = {"status": "ok", "path": str(path)}
    if missing:
        raise SyncError("missing project Skills: {}".format(", ".join(missing)))
    return checks


def _has_frontmatter_name(text: str, name: str) -> bool:
    pattern = r"^name:\s*{}\s*$".format(re.escape(name))
    return re.search(pattern, text, flags=re.MULTILINE) is not None


def _render_codex_config(
    project_root: Path,
    workspace_root: Path,
    workspace_db: Path,
    workspace_calendar: Path,
    python_executable: str,
    skill_path: Path,
) -> str:
    root = str(project_root)
    template = (
        "# Generated by `python -m mcp_server.cli sync`. Do not edit.\n\n"
        "[mcp_servers.fireagent]\n"
        "command = {command}\n"
        "args = [\"-m\", \"mcp_server.server\"]\n"
        "cwd = {root}\n"
        "startup_timeout_sec = 120\n"
        "tool_timeout_sec = 120\n"
        "enabled = true\n\n"
        "[mcp_servers.fireagent.env]\n"
        "PYTHONPATH = {root}\n"
        "A_STOCK_DATA_SKILL_PATH = {skill}\n"
        "FIREAGENT_WORKSPACE = {workspace}\n"
        "FIREAGENT_DB_PATH = {database}\n"
        "FIREAGENT_HOLIDAY_FILE = {calendar}\n"
    )
    return template.format(
        command=_toml_string(python_executable),
        root=_toml_string(root),
        skill=_toml_string(str(skill_path)),
        workspace=_toml_string(str(workspace_root)),
        database=_toml_string(str(workspace_db)),
        calendar=_toml_string(str(workspace_calendar)),
    )


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
